import { brandConfig } from "@/lib/brand";
import { featureFlags } from "@/lib/features";
import type { SitePayload } from "@/types/site";

export const seedSitePayload: SitePayload = {
  brand: brandConfig,
  features: featureFlags,
  settings: {
    announcementText: "Friday Fish Special All Day",
    heroEyebrow: "Local Restaurant Website System",
    heroHeadline: "Hometown Cooking, Served Fresh Daily",
    heroSubheadline:
      "Breakfast • Lunch • Dinner. Right here in De Soto, Illinois.",
    heroPrimaryCtaLabel: "View Menu",
    heroPrimaryCtaHref: "/menu",
    heroSecondaryCtaLabel: "Call Now",
    heroSecondaryCtaHref: "tel:+16188673175",
    quickInfoHoursLabel:
      "Tue-Thu 5:30 AM - 3:00 PM • Fri-Sat 5:30 AM - 8:00 PM • Sun 5:30 AM - 3:00 PM",
    orderingNotice:
      "Direct ordering, specials, menu items, and hours are all structured for owner editing.",
  },
  hours: [
    {
      id: "hours-1",
      dayLabel: "Tuesday - Thursday",
      openText: "5:30 AM - 3:00 PM",
      sortOrder: 1,
      isActive: true,
    },
    {
      id: "hours-2",
      dayLabel: "Friday - Saturday",
      openText: "5:30 AM - 8:00 PM",
      sortOrder: 2,
      isActive: true,
    },
    {
      id: "hours-3",
      dayLabel: "Sunday",
      openText: "5:30 AM - 3:00 PM",
      sortOrder: 3,
      isActive: true,
    },
  ],
  homePage: {
    heroImageUrl: "https://c.animaapp.com/mnysm4c6a1O30C/img/ai_1.png",
    specialsIntro:
      "This block is meant to drive same-day foot traffic. Keep one main special front and center.",
    featuredMenuTitle: "Local Favorites",
    featuredMenuIntro:
      "Big names, prices aligned right, and simple descriptions keep the menu easy to scan.",
  },
  aboutPage: {
    title: "A local spot built for regulars",
    body: [
      "This template is based on a practical diner site workflow: easy menu browsing, fast call-to-action paths, and content the owner can update without a developer.",
      "Use the same system for diners, bakeries, cafes, food trucks, sandwich shops, and other local food businesses by swapping the brand config, content, and feature toggles.",
    ],
  },
  specials: [
    {
      id: "special-1",
      title: "Country Fried Steak",
      description: "Served with mashed potatoes and gravy.",
      price: 9.99,
      label: "Today's Special",
      isActive: true,
      isFeatured: true,
      sortOrder: 1,
    },
    {
      id: "special-2",
      title: "Soup of the Day",
      description: "Ask the counter for today's fresh batch.",
      price: 3.99,
      label: "Soup",
      isActive: true,
      isFeatured: false,
      sortOrder: 2,
    },
    {
      id: "special-3",
      title: "Friday Fish Plate",
      description: "House favorite served with fries and slaw.",
      price: 12.99,
      label: "Weekend Feature",
      isActive: true,
      isFeatured: false,
      sortOrder: 3,
    },
  ],
  menuCategories: [
    {
      id: "breakfast",
      name: "Breakfast",
      slug: "breakfast",
      serviceWindow: "breakfast",
      isActive: true,
      sortOrder: 1,
      items: [
        {
          id: "biscuits-gravy",
          categoryId: "breakfast",
          name: "Biscuits & Gravy",
          description: "House-made sausage gravy over split biscuits.",
          price: 6.99,
          tags: ["Best Seller"],
          isActive: true,
          isSoldOut: false,
          isFeatured: true,
          sortOrder: 1,
          optionGroups: [],
        },
        {
          id: "breakfast-platter",
          categoryId: "breakfast",
          name: "Country Breakfast Plate",
          description: "Eggs, toast, choice of meat, and potatoes.",
          price: 8.99,
          tags: [],
          isActive: true,
          isSoldOut: false,
          isFeatured: false,
          sortOrder: 2,
          optionGroups: [],
        },
      ],
    },
    {
      id: "lunch",
      name: "Lunch & Sandwiches",
      slug: "lunch-sandwiches",
      serviceWindow: "lunch",
      isActive: true,
      sortOrder: 2,
      items: [
        {
          id: "patty-melt",
          categoryId: "lunch",
          name: "Patty Melt",
          description: "Grilled onions, Swiss, rye.",
          price: 8.99,
          tags: ["Popular"],
          isActive: true,
          isSoldOut: false,
          isFeatured: true,
          sortOrder: 1,
          optionGroups: [],
        },
        {
          id: "club-sandwich",
          categoryId: "lunch",
          name: "Club Sandwich",
          description: "Turkey, bacon, lettuce, tomato, mayo.",
          price: 8.49,
          tags: [],
          isActive: true,
          isSoldOut: false,
          isFeatured: false,
          sortOrder: 2,
          optionGroups: [],
        },
      ],
    },
    {
      id: "dinner",
      name: "Dinner Plates",
      slug: "dinner-plates",
      serviceWindow: "dinner",
      isActive: true,
      sortOrder: 3,
      items: [
        {
          id: "fried-chicken",
          categoryId: "dinner",
          name: "Fried Chicken Plate",
          description: "Crispy chicken, mashed potatoes, green beans.",
          price: 11.99,
          tags: ["House Favorite"],
          isActive: true,
          isSoldOut: false,
          isFeatured: true,
          sortOrder: 1,
          optionGroups: [],
        },
      ],
    },
  ],
  galleryImages: [
    {
      id: "gallery-1",
      src: "https://c.animaapp.com/mnysm4c6a1O30C/img/ai_1.png",
      alt: "Restaurant signature plate",
      sortOrder: 1,
      isActive: true,
    },
    {
      id: "gallery-2",
      src: "https://c.animaapp.com/mnysm4c6a1O30C/img/ai_2.png",
      alt: "Classic diner counter",
      sortOrder: 2,
      isActive: true,
    },
    {
      id: "gallery-3",
      src: "https://c.animaapp.com/mnysm4c6a1O30C/img/ai_3.png",
      alt: "Burger and fries",
      sortOrder: 3,
      isActive: true,
    },
  ],
  testimonials: [],
};
