import { brandConfig } from "@/lib/brand";
import { featureFlags } from "@/lib/features";
import type { SitePayload } from "@/types/site";

export const seedSitePayload: SitePayload = {
  brand: brandConfig,
  kitType: "restaurant",
  rendererType: "standard",
  features: {
    ...featureFlags,
    showBreakfastMenu: false,
    showLunchMenu: true,
    showDinnerMenu: true,
    showSpecials: true,
    showGallery: true,
    showTestimonials: false,
  },
  settings: {
    announcementText: "Weekend Brunch Special Now Live — Saturdays & Sundays from 11 AM",
    heroEyebrow: "South Lamar · Austin, TX",
    heroHeadline: "Wood-Fired Flavors. Neighborhood Warmth.",
    heroSubheadline:
      "Hand-crafted food over real fire. Open Tuesday through Sunday for lunch, dinner, and weekend brunch.",
    heroPrimaryCtaLabel: "View Menu",
    heroPrimaryCtaHref: "/preview/menu",
    heroSecondaryCtaLabel: "Get Directions",
    heroSecondaryCtaHref: "https://maps.google.com/?q=412+S+Lamar+Blvd+Austin+TX+78704",
    quickInfoHoursLabel:
      "Tue–Thu 11 AM – 10 PM  ·  Fri–Sat 11 AM – 11 PM  ·  Sun 11 AM – 9 PM  ·  Mon Closed",
    orderingNotice:
      "Walk-ins welcome. Reservations recommended Friday and Saturday evenings.",
  },
  hours: [
    {
      id: "hours-mon",
      dayLabel: "Monday",
      openText: "Closed",
      sortOrder: 1,
      isActive: true,
    },
    {
      id: "hours-tue-thu",
      dayLabel: "Tuesday – Thursday",
      openText: "11:00 AM – 10:00 PM",
      sortOrder: 2,
      isActive: true,
    },
    {
      id: "hours-fri-sat",
      dayLabel: "Friday – Saturday",
      openText: "11:00 AM – 11:00 PM",
      sortOrder: 3,
      isActive: true,
    },
    {
      id: "hours-sun",
      dayLabel: "Sunday",
      openText: "11:00 AM – 9:00 PM",
      sortOrder: 4,
      isActive: true,
    },
  ],
  homePage: {
    heroImageUrl: "https://c.animaapp.com/mnysm4c6a1O30C/img/ai_1.png",
    specialsIntro:
      "Our fire-side specials change daily. Ask your server what's coming off the oak tonight.",
    featuredMenuTitle: "From the Kitchen",
    featuredMenuIntro:
      "Everything on the menu is made in-house, cooked to order, and built around what's fresh this week.",
    galleryTitle: "Inside Ember & Oak",
    gallerySubtitle: "The fire's always going.",
    menuPreviewTitle: "Our Menu",
    menuPreviewSubtitle: "Starters through dessert — all cooked over real wood.",
    contactTitle: "Find Us",
    contactSubtitle: "South Lamar, right where it belongs.",
  },
  aboutPage: {
    title: "Cooking over fire since 2019",
    body: [
      "Ember & Oak opened its doors on South Lamar with one belief: great food tastes better when it's made over real fire. We slow-smoke, wood-fire, and cast-iron cook everything on our menu — no shortcuts, no reheating. Our kitchen runs on oak and applewood, and our philosophy runs on hospitality.",
      "We're rooted in the neighborhood and proud of it. Whether it's a Tuesday night ribeye or a lazy Sunday brunch, our doors are open, the fire's going, and the table is yours. Come as you are.",
    ],
  },
  specials: [
    {
      id: "special-1",
      title: "Herb-Crusted Lamb Rack",
      description:
        "Rosemary–garlic crust, red wine jus, roasted root vegetables. Limited — ask your server.",
      price: 38,
      label: "Tonight's Special",
      isActive: true,
      isFeatured: true,
      sortOrder: 1,
    },
    {
      id: "special-2",
      title: "Roasted Tomato Bisque",
      description:
        "Slow-roasted Roma tomatoes, fresh basil, crème fraîche, sourdough croutons.",
      price: 8,
      label: "Soup of the Day",
      isActive: true,
      isFeatured: false,
      sortOrder: 2,
    },
    {
      id: "special-3",
      title: "Ember Benedict",
      description:
        "Smoked pulled pork, poached eggs, chipotle hollandaise, griddled English muffin.",
      price: 16,
      label: "Weekend Brunch",
      isActive: true,
      isFeatured: false,
      sortOrder: 3,
    },
  ],
  menuCategories: [
    {
      id: "starters",
      name: "Starters",
      slug: "starters",
      serviceWindow: "all-day",
      isActive: true,
      sortOrder: 1,
      items: [
        {
          id: "whipped-ricotta",
          categoryId: "starters",
          name: "House Whipped Ricotta",
          description:
            "Grilled crostini, local wildflower honey, crushed red pepper flakes.",
          price: 12,
          tags: ["Fan Favorite"],
          isActive: true,
          isSoldOut: false,
          isFeatured: true,
          sortOrder: 1,
          optionGroups: [],
        },
        {
          id: "burrata",
          categoryId: "starters",
          name: "Burrata & Heirloom Tomato",
          description:
            "Fresh burrata, heirloom slices, basil oil, flaky sea salt, crostini.",
          price: 16,
          tags: ["Seasonal"],
          isActive: true,
          isSoldOut: false,
          isFeatured: false,
          sortOrder: 2,
          optionGroups: [],
        },
        {
          id: "smashed-fingerlings",
          categoryId: "starters",
          name: "Crispy Smashed Fingerlings",
          description:
            "Cast-iron fried fingerling potatoes, roasted garlic aioli, smoked paprika.",
          price: 10,
          tags: [],
          isActive: true,
          isSoldOut: false,
          isFeatured: false,
          sortOrder: 3,
          optionGroups: [],
        },
        {
          id: "ember-wings",
          categoryId: "starters",
          name: "Smoked Chicken Wings",
          description:
            "Oak-smoked, tossed in ember glaze, celery, house-made blue cheese.",
          price: 15,
          tags: ["Best Seller"],
          isActive: true,
          isSoldOut: false,
          isFeatured: true,
          sortOrder: 4,
          optionGroups: [],
        },
        {
          id: "artichoke-dip",
          categoryId: "starters",
          name: "Wood-Fired Artichoke Dip",
          description:
            "Roasted artichoke, parmesan cream, sourdough for dipping.",
          price: 14,
          tags: [],
          isActive: true,
          isSoldOut: false,
          isFeatured: false,
          sortOrder: 5,
          optionGroups: [],
        },
      ],
    },
    {
      id: "salads",
      name: "Salads",
      slug: "salads",
      serviceWindow: "all-day",
      isActive: true,
      sortOrder: 2,
      items: [
        {
          id: "oak-salad",
          categoryId: "salads",
          name: "The Oak Salad",
          description:
            "Mixed greens, candied walnuts, dried cherries, crumbled goat cheese, champagne vinaigrette.",
          price: 13,
          tags: ["House Signature"],
          isActive: true,
          isSoldOut: false,
          isFeatured: true,
          sortOrder: 1,
          optionGroups: [],
        },
        {
          id: "caesar",
          categoryId: "salads",
          name: "Classic Caesar",
          description:
            "House-made Caesar dressing, shaved parmesan, anchovy, sourdough crostini.",
          price: 12,
          tags: [],
          isActive: true,
          isSoldOut: false,
          isFeatured: false,
          sortOrder: 2,
          optionGroups: [],
        },
        {
          id: "wedge",
          categoryId: "salads",
          name: "Iceberg Wedge",
          description:
            "Crispy iceberg, bacon lardons, cherry tomatoes, red onion, blue cheese dressing.",
          price: 11,
          tags: [],
          isActive: true,
          isSoldOut: false,
          isFeatured: false,
          sortOrder: 3,
          optionGroups: [],
        },
      ],
    },
    {
      id: "mains",
      name: "Mains",
      slug: "mains",
      serviceWindow: "lunch",
      isActive: true,
      sortOrder: 3,
      items: [
        {
          id: "ember-burger",
          categoryId: "mains",
          name: "The Ember Burger",
          description:
            "Dry-aged beef blend, aged white cheddar, caramelized onions, ember sauce, butter lettuce, brioche bun. Served with fries.",
          price: 18,
          tags: ["Best Seller"],
          isActive: true,
          isSoldOut: false,
          isFeatured: true,
          sortOrder: 1,
          optionGroups: [],
        },
        {
          id: "mushroom-risotto",
          categoryId: "mains",
          name: "Wild Mushroom Risotto",
          description:
            "Seasonal wild mushroom blend, truffle oil, aged parmesan, baby arugula.",
          price: 22,
          tags: ["Vegetarian"],
          isActive: true,
          isSoldOut: false,
          isFeatured: false,
          sortOrder: 2,
          optionGroups: [],
        },
        {
          id: "shrimp-pasta",
          categoryId: "mains",
          name: "Blackened Shrimp Pasta",
          description:
            "Gulf shrimp, linguine, roasted pepper cream sauce, fresh herbs, parmesan.",
          price: 24,
          tags: [],
          isActive: true,
          isSoldOut: false,
          isFeatured: false,
          sortOrder: 3,
          optionGroups: [],
        },
        {
          id: "half-chicken",
          categoryId: "mains",
          name: "Oak-Smoked Half Chicken",
          description:
            "Free-range half chicken, slow-smoked over oak, roasted root vegetables, pan jus.",
          price: 26,
          tags: ["House Favorite"],
          isActive: true,
          isSoldOut: false,
          isFeatured: true,
          sortOrder: 4,
          optionGroups: [],
        },
        {
          id: "cast-iron-salmon",
          categoryId: "mains",
          name: "Cast Iron Salmon",
          description:
            "Skin-on Atlantic salmon, lemon-caper butter, wilted spinach, fingerling potatoes.",
          price: 28,
          tags: [],
          isActive: true,
          isSoldOut: false,
          isFeatured: false,
          sortOrder: 5,
          optionGroups: [],
        },
        {
          id: "ribeye",
          categoryId: "mains",
          name: "Hand-Cut Ribeye  (12 oz)",
          description:
            "Wood-fire finished, compound herb butter, roasted garlic mashed potatoes, seasonal vegetable.",
          price: 46,
          tags: ["Chef's Cut"],
          isActive: true,
          isSoldOut: false,
          isFeatured: false,
          sortOrder: 6,
          optionGroups: [],
        },
      ],
    },
    {
      id: "sides",
      name: "Sides",
      slug: "sides",
      serviceWindow: "all-day",
      isActive: true,
      sortOrder: 4,
      items: [
        {
          id: "mashed-potatoes",
          categoryId: "sides",
          name: "Roasted Garlic Mashed Potatoes",
          description: "Yukon gold, roasted garlic, butter, heavy cream.",
          price: 6,
          tags: [],
          isActive: true,
          isSoldOut: false,
          isFeatured: false,
          sortOrder: 1,
          optionGroups: [],
        },
        {
          id: "brussels-sprouts",
          categoryId: "sides",
          name: "Crispy Brussels Sprouts",
          description: "Wood-roasted, lemon tahini drizzle, toasted pine nuts.",
          price: 8,
          tags: [],
          isActive: true,
          isSoldOut: false,
          isFeatured: false,
          sortOrder: 2,
          optionGroups: [],
        },
        {
          id: "grilled-asparagus",
          categoryId: "sides",
          name: "Grilled Asparagus",
          description: "Fire-grilled, shaved parmesan, lemon zest.",
          price: 7,
          tags: [],
          isActive: true,
          isSoldOut: false,
          isFeatured: false,
          sortOrder: 3,
          optionGroups: [],
        },
        {
          id: "cornbread",
          categoryId: "sides",
          name: "Cast Iron Cornbread",
          description: "Jalapeño-flecked, whipped honey butter, served warm.",
          price: 5,
          tags: ["Popular"],
          isActive: true,
          isSoldOut: false,
          isFeatured: false,
          sortOrder: 4,
          optionGroups: [],
        },
      ],
    },
    {
      id: "desserts",
      name: "Desserts",
      slug: "desserts",
      serviceWindow: "dinner",
      isActive: true,
      sortOrder: 5,
      items: [
        {
          id: "lava-cake",
          categoryId: "desserts",
          name: "Warm Chocolate Lava Cake",
          description:
            "Dark chocolate, molten center, vanilla bean ice cream, powdered sugar.",
          price: 10,
          tags: ["Best Seller"],
          isActive: true,
          isSoldOut: false,
          isFeatured: true,
          sortOrder: 1,
          optionGroups: [],
        },
        {
          id: "creme-brulee",
          categoryId: "desserts",
          name: "Seasonal Crème Brûlée",
          description: "Classic custard, caramelized sugar crust, seasonal garnish.",
          price: 9,
          tags: [],
          isActive: true,
          isSoldOut: false,
          isFeatured: false,
          sortOrder: 2,
          optionGroups: [],
        },
        {
          id: "panna-cotta",
          categoryId: "desserts",
          name: "Buttermilk Panna Cotta",
          description:
            "Silky buttermilk set cream, fresh berry compote, candied lemon zest.",
          price: 8,
          tags: [],
          isActive: true,
          isSoldOut: false,
          isFeatured: false,
          sortOrder: 3,
          optionGroups: [],
        },
      ],
    },
    {
      id: "drinks",
      name: "Drinks",
      slug: "drinks",
      serviceWindow: "all-day",
      isActive: true,
      sortOrder: 6,
      items: [
        {
          id: "lemonade",
          categoryId: "drinks",
          name: "House Lemonade",
          description:
            "Fresh-squeezed, cane sugar, choice of classic or lavender.",
          price: 5,
          tags: [],
          isActive: true,
          isSoldOut: false,
          isFeatured: false,
          sortOrder: 1,
          optionGroups: [],
        },
        {
          id: "sweet-tea",
          categoryId: "drinks",
          name: "House-Brewed Sweet Tea",
          description: "Texas-style sweet tea, brewed fresh daily.",
          price: 4,
          tags: [],
          isActive: true,
          isSoldOut: false,
          isFeatured: false,
          sortOrder: 2,
          optionGroups: [],
        },
        {
          id: "sparkling-water",
          categoryId: "drinks",
          name: "Sparkling Water",
          description: "500ml, chilled.",
          price: 4,
          tags: [],
          isActive: true,
          isSoldOut: false,
          isFeatured: false,
          sortOrder: 3,
          optionGroups: [],
        },
        {
          id: "cold-brew",
          categoryId: "drinks",
          name: "Cold Brew Coffee",
          description: "Local roast, 24-hour steep, served over ice.",
          price: 5,
          tags: [],
          isActive: true,
          isSoldOut: false,
          isFeatured: false,
          sortOrder: 4,
          optionGroups: [],
        },
      ],
    },
  ],
  galleryImages: [
    {
      id: "gallery-1",
      src: "https://c.animaapp.com/mnysm4c6a1O30C/img/ai_1.png",
      alt: "Wood-fired ribeye resting on cast iron",
      sortOrder: 1,
      isActive: true,
    },
    {
      id: "gallery-2",
      src: "https://c.animaapp.com/mnysm4c6a1O30C/img/ai_2.png",
      alt: "The Ember & Oak dining room at night",
      sortOrder: 2,
      isActive: true,
    },
    {
      id: "gallery-3",
      src: "https://c.animaapp.com/mnysm4c6a1O30C/img/ai_3.png",
      alt: "Ember burger with fries",
      sortOrder: 3,
      isActive: true,
    },
  ],
  testimonials: [],
};
